### ISSUE TITLE
TorCrawl.py import error

### ISSUE THREAD

**Issue by guneetsura** [MikeMeliz/TorCrawl.py#21]
After executing command - python torcrawl.py -v -w -u http://www.github.com/ -c

This issue has been raised by terminal -->

> Failed to import '/usr/lib/libyara.so'
PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games;/usr/lib
Traceback (most recent call last):
  File "/home/kali/TorCrawl.py/torcrawl.py", line 57, in <module>
    from modules.extractor import extractor
  File "/home/kali/TorCrawl.py/modules/extractor.py", line 4, in <module>
    import yara as _yara
  File "/home/kali/.local/lib/python3.10/site-packages/yara/__init__.py", line 7, in <module>
    from yara.rules import compile
  File "/home/kali/.local/lib/python3.10/site-packages/yara/rules.py", line 17, in <module>
    from yara.libyara_wrapper import *
  File "/home/kali/.local/lib/python3.10/site-packages/yara/libyara_wrapper.py", line 315, in <module>
    libyaradll = cdll.LoadLibrary(library)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/libyara.so: cannot open shared object file: No such file or directory

**Comment by AlexanderWeismannn** [comment]
I'm having the same issue, any breakthroughs?

**Comment by MikeMeliz** [comment]
Super delayed answer on this, but many thanks @AlexanderWeismannn for finding the solution.

I changed the requirements.txt with this commit: https://github.com/MikeMeliz/TorCrawl.py/commit/e1a777ea996b8d38c2a36922adad7bf191d32d03
